input {
  kafka {
    bootstrap_servers => "kafka.local:9092"
    topics => ["zeek-group"]
    group_id => "zeek-group"
    auto_offset_reset => "earliest"
    codec => "json"
  }
}

filter {
  date {
    match => ["ts", "UNIX"]
    target => "@timestamp"
  }
  mutate {
    add_field => { "logstash_pipeline" => "zeek_pipeline" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch.local:9200"]
    index => "active-zeek"
    data_stream => false
    ilm_enabled => false
    manage_template => false
  }
}
